-- Run this in the Supabase SQL Editor to seed all services.
-- Uses upsert so it's safe to run multiple times.

insert into public.services (name, slug, category, description, sort_order, active) values
  ('Photocopying',                 'photocopying',                'Print',       'Fast, high-quality document reproduction for offices, schools, and individuals.',                      1,  true),
  ('Lamination',                   'lamination',                  'Print',       'Professional lamination to protect and enhance your documents and prints.',                             2,  true),
  ('Spiral Binding',               'spiral-binding',              'Publishing',  'Clean, durable spiral binding for reports, notebooks, and booklets.',                                   3,  true),
  ('ID Card Printing',             'id-card-printing',            'Print',       'Custom ID cards for schools, businesses, and organisations — printed same day.',                        4,  true),
  ('Business Cards',               'business-cards',              'Print',       'Premium business cards that make a lasting first impression.',                                           5,  true),
  ('Letterheads',                  'letterheads',                 'Print',       'Branded letterheads that give your business a professional identity.',                                  6,  true),
  ('Roll-Up Banners',              'roll-up-banners',             'Signage',     'Portable, high-impact banners ideal for events, exhibitions, and promotions.',                          7,  true),
  ('Banners & Signages',           'banners-signages',            'Signage',     'Eye-catching banners and signage for indoor and outdoor use.',                                           8,  true),
  ('Mug Printing',                 'mug-printing',                'Gifts',       'Personalised mugs for gifts, events, and brand promotion.',                                             9,  true),
  ('Souvenir Printing',            'souvenir-printing',           'Gifts',       'Custom souvenirs and promotional items for every occasion.',                                            10, true),
  ('Screen Printing',              'screen-printing',             'Apparel',     'Vibrant, durable screen printing on t-shirts, aprons, and other surfaces.',                            11, true),
  ('Book Printing',                'book-printing',               'Publishing',  'High-quality book printing for authors, schools, churches, and publishers.',                            12, true),
  ('Exercise Books',               'exercise-books',              'Publishing',  'Custom exercise books branded for schools and institutions.',                                            13, true),
  ('Office Stationery',            'office-stationery',           'Print',       'Complete stationery printing — notepads, receipts, forms, and more.',                                  14, true),
  ('CV / Application Letter Typing','cv-application-letter-typing','Design',     'Professional typing, formatting, and design of CVs and application letters.',                           15, true),
  ('Internet Services',            'internet-services',           'Design',      'Reliable internet access for browsing, research, and online tasks.',                                   16, true),
  ('Scanning',                     'scanning',                    'Print',       'High-resolution document and photo scanning to digital formats.',                                       17, true),
  ('Document Editing',             'document-editing',            'Design',      'Professional editing and formatting of business and academic documents.',                               18, true),
  ('Photo Editing',                'photo-editing',               'Design',      'Expert photo retouching, enhancement, colour correction, and restoration.',                            19, true),
  ('Branding Services',            'branding-services',           'Design',      'Comprehensive branding packages — logos, style guides, and brand assets.',                             20, true),
  ('Vinyl Stickers',               'vinyl-stickers',              'Signage',     'Custom vinyl stickers for branding, product labelling, and decoration.',                               21, true),
  ('Vehicle Branding',             'vehicle-branding',            'Signage',     'Transform your vehicle into a mobile billboard for maximum brand exposure.',                            22, true),
  ('Large Format Printing',        'large-format-printing',       'Signage',     'Large-scale prints for banners, backdrops, billboards, and more.',                                     23, true),
  ('Stamp Making',                 'stamp-making',                'Print',       'Custom rubber and self-inking stamps for businesses and individuals.',                                  24, true),
  ('Customized Jerseys',           'customized-jerseys',          'Apparel',     'Fully customised jerseys for football teams, schools, and corporate events.',                           25, true),
  ('Customized Polo Shirts',       'customized-polo-shirts',      'Apparel',     'Branded polo shirts for corporate uniforms, groups, and promotions.',                                  26, true),
  ('Embroidery Services',          'embroidery-services',         'Embroidery',  'Premium embroidery on shirts, caps, bags, and accessories.',                                           27, true),
  ('Invitation Cards',             'invitation-cards',            'Print',       'Elegant invitation cards for weddings, parties, graduations, and corporate events.',                   28, true),
  ('Church Programmes',            'church-programmes',           'Publishing',  'Beautifully designed programmes for church services, crusades, and events.',                           29, true),
  ('Funeral Brochures',            'funeral-brochures',           'Publishing',  'Dignified and thoughtfully designed brochures to honour your loved ones.',                             30, true),
  ('Calendars & Diaries',          'calendars-diaries',           'Print',       'Branded calendars and diaries to keep your business visible all year round.',                          31, true),
  ('Passport & Visa Assistance',   'passport-visa-assistance',    'Design',      'Professional assistance with passport photos and visa application documentation.',                     32, true),
  ('Computer Designing',           'computer-designing',          'Design',      'Creative graphic design for flyers, posters, brochures, and all print materials.',                     33, true),
  ('Digital Printing',             'digital-printing',            'Print',       'Full-colour digital printing with fast turnaround and sharp, accurate results.',                       34, true),
  ('Colour Printing',              'colour-printing',             'Print',       'Vibrant full-colour printing for documents, flyers, posters, and more.',                               35, true),
  ('Black & White Printing',       'black-white-printing',        'Print',       'Affordable black and white printing for documents, handouts, and copies.',                             36, true)
on conflict (slug) do update set
  name        = excluded.name,
  category    = excluded.category,
  description = excluded.description,
  sort_order  = excluded.sort_order,
  active      = excluded.active;
